pipeline {
  
	    agent any
         
           tools {
                 maven "3.8.6"
                }
            

                 stages {


	            stage ('Build') {
	                steps {
                              dir("cidr_convert_api/java/cidr-api"){

                               script{                   
                               sh 'mvn -B -DskipTests clean package'
                                 }
                                  }
                          }
			         
	                }
	           
	  
                    stage ('SonarQube Analysis'){
                        steps {
                                dir("cidr_convert_api/java/cidr-api") {
                                      withSonarQubeEnv('sonarqube') {
                                          sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
                                                    }
                                                }
                    

                                               }
              

                                          } 


	            stage ('Create docker image') {
	                steps {
	                 echo "creando docker"
	                }
	

	            }
	        }
	}
