pipeline {
  
	    agent {
                docker {
                      image "maven:3.6.0-jdk-13" 
                      args "-v /root/.m2:/root/.m2" 
                         }

                      }   
            

                 stages {


	            stage ('Build') {
	                steps {
                              dir("cidr_convert_api/java/cidr-api"){

                               script{                   
                               sh 'mvn clean package'
                                 }
                                  }
                          }
			         
	                }
	           
	  
	            stage ('Create docker image') {
	                steps {
	                 echo "creando docker"
	                }
	

	            }
	        }
	}
