pipeline {
	    agent {
                docker {
                      image 'maven:3.8.1-adoptopenjdk-11' 
                      args '-v /root/.m2:/root/.m2' 
                         }

                      }   
            

                 stages {


	            stage ('Build') {
	                steps {
                              dir("cidr_convert_api/java/cidr-api"){

                               script{                   
                               sh 'mvn clean package -DskipTests'
                                 }
                                  }
                          }
			         
	                }
	           
	  
	            stage ('Create docker image') {
	                steps {
	                 echo "creando docker"
	                }
	

	            }
	        }
	}
